#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtstyleplugins
Version  : 1
Release  : 1
URL      : https://github.com/qt/qtstyleplugins/tarball/master
Source0  : https://github.com/qt/qtstyleplugins/tarball/master
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0-or-later
Requires: qtstyleplugins-lib = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Widgets)

%description
No detailed description available

%package dev
Summary: dev components for the qtstyleplugins package.
Group: Development
Requires: qtstyleplugins-lib = %{version}-%{release}
Provides: qtstyleplugins-devel = %{version}-%{release}
Requires: qtstyleplugins = %{version}-%{release}

%description dev
dev components for the qtstyleplugins package.


%package lib
Summary: lib components for the qtstyleplugins package.
Group: Libraries

%description lib
lib components for the qtstyleplugins package.


%prep
%setup -q -n qt-qtstyleplugins-335dbec
cd %{_builddir}/qt-qtstyleplugins-335dbec

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake -config ltcg -config fat-static-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1586782281
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/cmake/Qt5Widgets/Qt5Widgets_QBB10StylePlugin.cmake
/usr/lib64/cmake/Qt5Widgets/Qt5Widgets_QCleanlooksStylePlugin.cmake
/usr/lib64/cmake/Qt5Widgets/Qt5Widgets_QMotifStylePlugin.cmake
/usr/lib64/cmake/Qt5Widgets/Qt5Widgets_QPlastiqueStylePlugin.cmake

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/styles/libbb10styleplugin.so
/usr/lib64/qt5/plugins/styles/libqcleanlooksstyle.so
/usr/lib64/qt5/plugins/styles/libqmotifstyle.so
/usr/lib64/qt5/plugins/styles/libqplastiquestyle.so
